server:
  port: 8080
  servlet:
    context-path: /dis
    
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: name=loan-distribute
  http:
    encoding:
      charset: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz96u8tv73608suh5.mysql.rds.aliyuncs.com:3306/loan_cps?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: zhang
    password: 102115Zh
    hikari:
      minimum-idle: 20
      maximum-pool-size: 1000
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 6000000
      connection-timeout: 5000
      connection-test-query: select 1
  redis:
    host: r-wz9m127ioxtdjhetfr.redis.rds.aliyuncs.com
    port: 6379
    password: 102115Zh
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-active: 200
        min-idle: 20
        max-idle: 100
        max-wait: 3000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath*:mybatis/mapper/*/*.xml
mongodb:
  config:
    url: mongodb://root:102115Zh@dds-wz93f5c4e5b127541.mongodb.rds.aliyuncs.com:3717,dds-wz93f5c4e5b127542.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-42670473
    dbName: cps

logging:
  file:
    name: /data/logs/distribute/distribute.log
  level:
    root: info
    sql: info
    web: warn
    org.quartz: warn
    org.hibernate: warn
    org.hibernate.jpa: warn
    com.zaxxer: warn
    org.springframework: warn
    org.springframework.boot: warn
    org.apache: warn
    com.dy.springboot.server.mapper: warn
    springfox.documentation: warn
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}]-[%thread]-%-5level-%logger{20}-%msg%n'
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}]-[%thread]-%-5level-%logger{20}-%msg%n'
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

