server:
  port: 8082
  servlet:
    context-path: /dis

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: name=loan-distribute
  http:
    encoding:
      charset: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp13fc5831y3xut83ko.mysql.rds.aliyuncs.com:3306/loan_cps?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 102115Zh
    hikari:
      minimum-idle: 20
      maximum-pool-size: 1000
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 6000000
      connection-timeout: 5000
      connection-test-query: select 1
  redis:
    host: r-bp1mudl1fkwuqk2syxpd.redis.rds.aliyuncs.com
    port: 6379
    password: 102115Zh
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-active: 100
        min-idle: 20
        max-idle: 100
        max-wait: 3000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath*:mybatis/mapper/*/*.xml

mongodb:
  config:
    url: mongodb://root:102115Zh@dds-bp11cf64bb5686e41205-pub.mongodb.rds.aliyuncs.com:3717,dds-bp11cf64bb5686e42288-pub.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-45103935
    dbName: cps

logging:
  file:
    name: /data/logs/distribute-test/distribute.log
  level:
    root: info
    sql: info
    web: info
    org.quartz: warn
    org.hibernate: warn
    org.hibernate.jpa: warn
    com.zaxxer: warn
    org.springframework: info
    org.springframework.boot: info
    org.apache: warn
    com.dy.springboot.server.mapper: warn
    springfox.documentation: warn
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}][%thread]%-5level-%logger{10}-%msg%n'
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}][%thread]%-5level-%logger{10}-%msg%n'
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

